FROM node:12.7-alpine AS build
WORKDIR /java_course_work_front
COPY ./package.json ./package-lock.json ./
COPY ./ .
RUN npm install
RUN npm run build

from nginx:1.20
COPY --from=build ./dist /usr/share/nginx/html
