FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./

#RUN npm install
#RUN npm install keycloak-js jwt-decode @baloise/vue-keycloak
COPY ./ .
#RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
RUN apt-get update -qq && apt-get -y install curl
COPY ./consul-template /usr/bin/consul-template

RUN mkdir -p /consul-template /consul-template/config.d /consul-template/templates && \
    rm /etc/nginx/conf.d/*
ENV CONSUL consul:8500

#COPY --from=build-stage /app/dist /app
COPY --from=build-stage /app/dist /usr/share/nginx/html
CMD /usr/sbin/nginx -c /etc/nginx/nginx.conf && consul-template -consul-addr=$CONSUL -template "/etc/consul-templates/default.conf.ctmpl:/etc/nginx/conf.d/app.conf:/usr/sbin/nginx -s reload"
#COPY nginx.conf /etc/nginx/nginx.conf